name: Deploy to  LWS 

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /biofarmtrading/
          exclude: |
            - '**/.git/*'
            - '**/.git/**'
            - 'node_modules/*'
            - '.env'
            - '.env.example'
            - 'phpunit.xml'
            - 'README.md'
            - 'tests/**'

            