name: Deploy to  LWS 

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader

      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./biofarmtrading/
          exclude: |
            - '**/.git/*'
            - '**/.git/**'
            - 'node_modules/*'
            - '.env'
            - '.env.example'
            - 'phpunit.xml'
            - 'README.md'
            - 'tests/**'
            - 'vendor.zip'

            